#!/bin/bash

native-image \
    -jar target/tools-clj-0.0.1-standalone.jar \
    -H:+ReportExceptionStackTraces \
    --features=clj_easy.graal_build_time.InitClojureClasses \
    --verbose \
    --no-fallback \
    -o tcl