#!/bin/bash

VERSION=0.0.2

echo "VERSION: $VERSION"

clojure -T:build clean

echo "clean done"

clojure -T:build uber

echo "build uber jar done"

native-image \
    -jar "target/tools-clj-$VERSION-standalone.jar" \
    -J-Dfile.encoding=UTF-8 \
    -J-Dstdout.encoding=UTF-8 \
    -J-Dstderr.encoding=UTF-8 \
    -J-Dconsole.encoding=UTF-8 \
    -H:+AddAllCharsets \
    -H:+ReportExceptionStackTraces \
    -H:ResourceConfigurationFiles=native-config/resource-config_darwin_arm64.json \
    --enable-http \
    --enable-https \
    --features=clj_easy.graal_build_time.InitClojureClasses \
    --initialize-at-build-time=com.fasterxml.jackson.dataformat.cbor.CBORFactoryBuilder \
    --initialize-at-build-time=com.fasterxml.jackson.core.StreamReadFeature \
    --initialize-at-build-time=com.fasterxml.jackson.dataformat.cbor.CBORFactory \
    --initialize-at-build-time=com.fasterxml.jackson.core.JsonGenerator \
    --initialize-at-build-time=com.fasterxml.jackson.dataformat.smile.SmileFactory \
    --initialize-at-build-time=com.fasterxml.jackson.core.json.JsonReadFeature \
    --initialize-at-build-time=com.fasterxml.jackson.core.io.SerializedString \
    --initialize-at-build-time=com.fasterxml.jackson.core.TSFBuilder \
    --initialize-at-build-time=com.fasterxml.jackson.core.JsonFactory \
    --initialize-at-build-time=com.fasterxml.jackson.core.io.CharTypes \
    --initialize-at-build-time=com.fasterxml.jackson.dataformat.smile.SmileFactoryBuilder \
    --initialize-at-build-time=com.fasterxml.jackson.core.io.JsonStringEncoder \
    --initialize-at-build-time=com.fasterxml.jackson.core.PrettyPrinter \
    --initialize-at-build-time=com.fasterxml.jackson.core.json.JsonWriteFeature \
    --initialize-at-build-time=com.fasterxml.jackson.core.base.ParserMinimalBase,com.fasterxml.jackson.core.json.ReaderBasedJsonParser,com.fasterxml.jackson.core.io.ContentReference,com.fasterxml.jackson.core.util.BufferRecyclers,com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.core.io.NumberInput,com.fasterxml.jackson.core.base.ParserBase,com.fasterxml.jackson.core.JsonToken,com.fasterxml.jackson.core.json.JsonParserBase \
    --verbose \
    --no-fallback \
    -o bin/tcl
