#!/bin/bash

clojure -T:build uber

TOOLS_CLJ_VERSION=$(cat ./VERSION)

native-image \
    -jar "target/tools-clj-$TOOLS_CLJ_VERSION-standalone.jar" \
    -H:+ReportExceptionStackTraces \
    --features=clj_easy.graal_build_time.InitClojureClasses \
    --verbose \
    --no-fallback \
    -o tcl